---
language: go

go:
  - "1.13"

git:
  depth: 1

script:
  - GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic ./sync ./concurrency

after_success:
  - bash <(curl -s https://codecov.io/bash)
